apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: panel-seg
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/your-org/panel-seg
    newName: ghcr.io/your-org/panel-seg
    newTag: latest
